name: Build visual-chatgpt

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    # Name of the job which will be shown on the web console
    name: Build and Push Docker Image
    # Use a list of labels to determine which runner the workflow will run on
    runs-on:
      - ubuntu-latest
    # Global environment variables
    env:
      RT_CDH_REGISTRY: "artifactory.cloud.ingka-system.cn"
      IMAGE_FULL_NAME: "artifactory.cloud.ingka-system.cn/cn-digital-hub-docker-dev-local/platform/visual-chatgpt:latest"   # put your production name here

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE on runner, so your workflow can access it
      - uses: actions/checkout@v2

       # To build and push Docker image with Buildx with full support of the features provided by Moby BuildKit builder toolkit
      - name: Build and push
        #id: A unique identifier for the step. You can use the id to reference the step in contexts
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # push: Push the build result to registry, default: false
          context: ./visual-chatgpt
          push: true
          tags: "sh777/vistual-chatgpt"
      #    # Do not use cache when building the image
          no-cache: true
          # secrets: Set the variables which will be delivered to Dockerfile to build Java
