name: Build and Push actions runner Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env: 
      DOCKER_REPOSITORY_NAME: sh777
      DOCKER_IMAGE_NAME: actions-runner
      DOCKER_TAG_PREFIX: 1.0.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.DOCKER_REPOSITORY_NAME}}/${{env.DOCKER_IMAGE_NAME}}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix={{branch}}-
            type=raw,${{ steps.extract-tag.outputs.result }}
          flavor: |
            latest=true
            prefix=${{ env.DOCKER_TAG_PREFIX }}          

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./actions-runner/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: ${{ steps.meta.outputs.images }}:latest
          cache-to: type=inline
